- name: install ansible and Heketi utilities
  yum: name={{ item }} state=present
  with_items:
    - heketi-client
    - heketi-templates
    - heketi
    - python-heketi

- name: copy private key
  copy: src=insecure_private_key owner=heketi group=heketi dest=/etc/heketi force=yes mode=600

- name: copy heketi configuration
  copy: src=heketi.json owner=root group=root dest=/etc/heketi force=yes mode=644

- name: copy files
  copy: src={{ item }} owner=vagrant group=vagrant dest=/home/vagrant force=yes mode=644
  with_items:
    - topology_libvirt.json
    - topology_virtualbox.json

- name: start heketi service 
  service: name=heketi state=started enabled=yes
